name: audio_client
description: "Notification system client application"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.4.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter
  ffmpeg_kit_flutter: 6.0.0
  rxdart: 0.27.7
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  web_socket_channel: ^2.4.0
  get_it: ^7.6.4
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.46
  just_audio_windows: ^0.2.2
  audio_session: ^0.1.14
  shared_preferences: ^2.0.17
  dio: ^5.0.3
  flutter_treeview:
    path: patched_packages/flutter_treeview
  flutter_localizations:
    sdk: flutter
  intl: 0.19.0
  font_awesome_flutter: ^10.6.0
  shelf: 1.4.1
  record: 6.0.0
  path_provider: 2.1.3
  synchronized: 3.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.0
  build_runner: any

flutter:
  uses-material-design: true
  generate: true
