name: audio_client
description: "Client application for playing sounds"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0-70.0.dev

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  web_socket_channel: ^2.4.0
  get_it: ^7.6.4
  logger: ^2.0.2
  cupertino_icons: ^1.0.8
  just_audio: ^0.10.3
  just_audio_media_kit: ^2.1.0
  media_kit_libs_windows_audio: ^1.0.9
  audio_session: ^0.1.14
  shared_preferences: ^2.0.17
  dio: ^5.0.3
  flutter_treeview: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any

flutter:
  uses-material-design: true
